export default {
	TOGGLE_ARTICLE_SNACKBAR: 'TOGGLE_ARTICLE_SNACKBAR',
	TOGGLE_COMMENT_DIALOG: 'TOGGLE_COMMENT_DIALOG', 
	TOGGLE_ARTICLE_DIALOG: 'TOGGLE_ARTICLE_DIALOG', 
	SET_OFF_SET: 'SET_OFF_SET'
};
