export default {
	FETCH_ARTICLE_REQUEST: 'FETCH_ARTICLE_REQUEST',
	FETCH_ARTICLE_DONE: 'FETCH_ARTICLE_DONE',
	FETCH_ARTICLE_ERROR: 'FETCH_ARTICLE_ERROR',

	CREATE_ARTICLE_REQUEST: 'CREATE_ARTICLE_REQUEST',
	CREATE_ARTICLE_DONE: 'CREATE_ARTICLE_DONE',
	CREATE_ARTICLE_ERROR: 'CREATE_ARTICLE_ERROR',

	UPDATE_ARTICLE_REQUEST: 'UPDATE_ARTICLE_REQUEST',
	UPDATE_ARTICLE_DONE: 'UPDATE_ARTICLE_DONE',
	UPDATE_ARTICLE_ERROR: 'UPDATE_ARTICLE_ERROR',

	DELETE_ARTICLE_REQUEST: 'DELETE_ARTICLE_REQUEST',
	DELETE_ARTICLE_DONE: 'DELETE_ARTICLE_DONE',
	DELETE_ARTICLE_ERROR: 'DELETE_ARTICLE_ERROR',

	UNLOAD_ARTICLE: 'UNLOAD ARTICLE',

	CLEAR_ARTICLE_ERROR: 'CLEAR_ARTICLE_ERROR'
};
