export default {
	FETCH_COMMENTS_FROM_ARTICLE_REQUEST: 'FETCH_COMMENTS_FROM_ARTICLE_REQUEST',
	FETCH_COMMENTS_FROM_ARTICLE_DONE: 'FETCH_COMMENTS_FROM_ARTICLE_DONE',
	FETCH_COMMENTS_FROM_ARTICLE_ERROR: 'FETCH_COMMENTS_FROM_ARTICLE_ERROR',

	ADD_COMMENT_TO_ARTICLE_REQUEST: 'ADD_COMMENT_TO_ARTICLE_REQUEST',
	ADD_COMMENT_TO_ARTICLE_DONE: 'ADD_COMMENT_TO_ARTICLE_DONE',
	ADD_COMMENT_TO_ARTICLE_ERROR: 'ADD_COMMENT_TO_ARTICLE_ERROR',

	REMOVE_COMMENT_FROM_ARTICLE_REQUEST: 'REMOVE_COMMENT_FROM_ARTICLE_REQUEST',
	REMOVE_COMMENT_FROM_ARTICLE_DONE: 'REMOVE_COMMENT_FROM_ARTICLE_DONE',
	REMOVE_COMMENT_FROM_ARTICLE_ERROR: 'REMOVE_COMMENT_FROM_ARTICLE_ERROR',

	UNLOAD_COMMENTS_FROM_ARTICLE: 'UNLOAD_COMMENTS_FROM_ARTICLE',

	CLEAR_COMMENTS_ERROR: 'CLEAR_COMMENTS_ERROR'
};
