export default {
	FETCH_ARTICLES_BY_MOST_RECENT_REQUEST: 'FETCH_ARTICLES_BY_MOST_RECENT_REQUEST',
	FETCH_ARTICLES_BY_MOST_RECENT_DONE: 'FETCH_ARTICLES_BY_MOST_RECENT_DONE',
	FETCH_ARTICLES_BY_MOST_RECENT_ERROR: 'FETCH_ARTICLES_BY_MOST_RECENT_ERROR',

	FETCH_FAVORITE_ARTICLES_REQUEST: 'FETCH_FAVORITE_ARTICLES_REQUEST',
	FETCH_FAVORITE_ARTICLES_DONE: 'FETCH_FAVORITE_ARTICLE_DONE',
	FETCH_FAVORITE_ARTICLES_ERROR: 'FETCH_FAVORITE_ARTICLE_ERROR',

	FETCH_ARTICLES_BY_AUTHOR_REQUEST: 'FETCH_ARTICLES_BY_AUTHOR_REQUEST',
	FETCH_ARTICLES_BY_AUTHOR_DONE: 'FETCH_ARTICLES_BY_AUTHOR_DONE',
	FETCH_ARTICLES_BY_AUTHOR_ERROR: 'FETCH_ARTICLES_BY_AUTHOR_ERROR',

	FETCH_ARTICLES_BY_TAG_REQUEST: 'FETCH_ARTICLES_BY_TAG_REQUEST',
	FETCH_ARTICLES_BY_TAG_DONE: 'FETCH_ARTICLES_BY_TAG_DONE',
	FETCH_ARTICLES_BY_TAG_ERROR: 'FETCH_ARTICLES_BY_TAG_ERROR',

	ADD_ARTICLE_TO_FAVORITES_REQUEST: 'ADD_ARTICLE_TO_FAVORITES_REQUEST',
	ADD_ARTICLE_TO_FAVORITES_DONE: 'ADD_ARTICLE_TO_FAVORITES_DONE',
	ADD_ARTICLE_TO_FAVORITES_ERROR: 'ADD_ARTICLE_TO_FAVORITES_ERROR',

	REMOVE_ARTICLE_FROM_FAVORITES_REQUEST: 'REMOVE_ARTICLE_FROM_FAVORITES_REQUEST',
	REMOVE_ARTICLE_FROM_FAVORITES_DONE: 'REMOVE_ARTICLE_FROM_FAVORITES_DONE',
	REMOVE_ARTICLE_FROM_FAVORITES_ERROR: ' REMOVE_ARTICLE_FROM_FAVORITES_ERROR',

	UNLOAD_ARTICLES: 'UNLOAD ARTICLES',

	CLEAR_ARTICLES_ERROR: 'CLEAR_ARTICLES_ERROR'
};
