export default {
    FETCH_ARTICLES_BY_MOST_RECENT_REQUESTED : 'FETCH_ARTICLES_BY_MOST_RECENT_REQUESTED',
    FETCH_ARTICLES_BY_MOST_RECENT_DONE : 'FETCH_ARTICLES_BY_MOST_RECENT_DONE',
    FETCH_ARTICLES_BY_MOST_RECENT_ERROR : 'FETCH_ARTICLES_BY_MOST_RECENT_ERROR',
    UNLOAD_ARTICLES_BY_MOST_RECENT : 'UNLOAD_ARTICLES_BY_MOST_RECENT',

    FETCH_FAVORITE_ARTICLES_REQUESTED: 'FETCH_FAVORITE_ARTICLES_REQUESTED',
    FETCH_FAVORITE_ARTICLES_DONE: 'FETCH_FAVORITE_ARTICLE_DONE',
    FETCH_FAVORITE_ARTICLES_ERROR: 'FETCH_FAVORITE_ARTICLE_ERROR',

	FETCH_ARTICLES_BY_AUTHOR_REQUESTED: 'FETCH_ARTICLES_BY_AUTHOR_REQUESTED',
    FETCH_ARTICLES_BY_AUTHOR_DONE: 'FETCH_ARTICLES_BY_AUTHOR_DONE',
    FETCH_ARTICLES_BY_AUTHOR_ERROR: 'FETCH_ARTICLES_BY_AUTHOR_ERROR',

    FETCH_ARTICLES_BY_TAG_REQUESTED: 'FETCH_ARTICLES_BY_TAG_REQUESTED',
    FETCH_ARTICLES_BY_TAG_DONE: 'FETCH_ARTICLES_BY_TAG_DONE',
    FETCH_ARTICLES_BY_TAG_ERROR: 'FETCH_ARTICLES_BY_TAG_ERROR',
    FETCH_ARTICLES_BY_TAG_UNMOUNTED: 'FETCH_ARTICLES_BY_TAG_UNMOUNTED',
    UNLOAD_ARTICLES_BY_TAG: 'UNLOAD_ARTICLES_BY_TAG_',
    
    FAVORITE_ARTICLE_REQUEST: 'FAVORITE_ARTICLE_REQUEST',
    FAVORITE_ARTICLE_DONE: 'FAVORITE_ARTICLE_DONE',
    FAVORITE_ARTICLE_ERROR: 'FAVORITE_ARTICLE_ERROR',

    UNFAVORITE_ARTICLE_REQUEST: 'UNFAVORITE_ARTICLE_REQUEST',
    UNFAVORITE_ARTICLE_DONE: 'UNFAVORITE_ARTICLE_DONE',
    UNFAVORITE_ARTICLE_ERROR: 'UNFAVORITE_ARTICLE_ERROR',

    UNLOAD_ARTICLES: 'UNLOAD ARTICLES'

    
};
