export default {
    FETCH_ARTICLES_BY_MOST_RECENT_REQUESTED : 'FETCH_ARTICLES_BY_MOST_RECENT_REQUESTED',
    FETCH_ARTICLES_BY_MOST_RECENT_DONE : 'FETCH_ARTICLES_BY_MOST_RECENT_DONE',
    FETCH_ARTICLES_BY_MOST_RECENT_FAILURE : 'FETCH_ARTICLES_BY_MOST_RECENT_FAILURE',
    UNLOAD_ARTICLES_BY_MOST_RECENT : 'UNLOAD_ARTICLES_BY_MOST_RECENT',

	/* FETCH_ARTICLES_REQUESTED: 'FETCH_ARTICLES_REQUESTED',
	FETCH_ARTICLES_DONE: 'FETCH_ARTICLES_DONE',
	FETCH_ARTICLES_FAILURE: 'FETCH_ARTICLES_FAILURE',
 */
    FETCH_FAVORITE_ARTICLES_REQUESTED: 'FETCH_FAVORITE_ARTICLES_REQUESTED',
    FETCH_FAVORITE_ARTICLES_DONE: 'FETCH_FAVORITE_ARTICLE_DONE',
    FETCH_FAVORITE_ARTICLES_FAILURE: 'FETCH_FAVORITE_ARTICLE_FAILURE',

	FETCH_ARTICLES_BY_AUTHOR_REQUESTED: 'FETCH_ARTICLES_BY_AUTHOR_REQUESTED',
    FETCH_ARTICLES_BY_AUTHOR_DONE: 'FETCH_ARTICLES_BY_AUTHOR_DONE',
    FETCH_ARTICLES_BY_AUTHOR_FAILURE: 'FETCH_ARTICLES_BY_AUTHOR_FAILURE',

    FETCH_ARTICLES_BY_TAG_REQUESTED: 'FETCH_ARTICLES_BY_TAG_REQUESTED',
    FETCH_ARTICLES_BY_TAG_DONE: 'FETCH_ARTICLES_BY_TAG_DONE',
    FETCH_ARTICLES_BY_TAG_FAILURE: 'FETCH_ARTICLES_BY_TAG_FAILURE',
    FETCH_ARTICLES_BY_TAG_UNMOUNTED: 'FETCH_ARTICLES_BY_TAG_UNMOUNTED',
    UNLOAD_ARTICLES_BY_TAG: 'UNLOAD_ARTICLES_BY_TAG_',
    
    ARTICLE_FAVORITED_REQUESTED: 'ARTICLE_FAVORITED_REQUESTED',
    ARTICLE_FAVORITED_DONE: 'ARTICLE_FAVORITED_DONE',
    ARTICLE_FAVORITED_FAILURE: 'ARTICLE_FAVORITED_FAILURE',

    ARTICLE_UNFAVORITED_REQUESTED: 'ARTICLE_UNFAVORITED_REQUESTED',
    ARTICLE_UNFAVORITED_DONE: 'ARTICLE_UNFAVORITED_DONE',
    ARTICLE_UNFAVORITED_FAILURE: 'ARTICLE_UNFAVORITED_FAILURE',

    UNLOAD_ARTICLES: 'UNLOAD ARTICLES'

    
};
