export default {

 FETCH_COMMENTS_FROM_ARTICLE_REQUESTED : 'FETCH_COMMENTS_FROM_ARTICLE_REQUESTED',
 FETCH_COMMENTS_FROM_ARTICLE_DONE :'FETCH_COMMENTS_FROM_ARTICLE_DONE',
 FETCH_COMMENTS_FROM_ARTICLE_FAILURE : 'FETCH_COMMENTS_FROM_ARTICLE_FAILURE',
 FETCH_COMMENTS_FROM_ARTICLE_UNMOUNTED : 'FETCH_COMMENTS_FROM_ARTICLE_UNMOUNTED',

 ADD_COMMENT_TO_ARTICLE_REQUESTED : 'ADD_COMMENT_TO_ARTICLE_REQUESTED',
 ADD_COMMENT_TO_ARTICLE_DONE : 'ADD_COMMENT_TO_ARTICLE_DONE',
 ADD_COMMENT_TO_ARTICLE_FAILURE : 'ADD_COMMENT_TO_ARTICLE_FAILURE',

 REMOVE_COMMENT_FROM_ARTICLE_REQUESTED : 'REMOVE_COMMENT_FROM_ARTICLE_REQUESTED',
 REMOVE_COMMENT_FROM_ARTICLE_DONE : 'REMOVE_COMMENT_FROM_ARTICLE_DONE',
 REMOVE_COMMENT_FROM_ARTICLE_ERROR : ' REMOVE_COMMENT_FROM_ARTICLE_ERROR'


}