export default {
    
	FETCH_PROFILE_BY_USERNAME_REQUEST: 'FETCH_PROFILE_BY_USERNAME_REQUEST',
	FETCH_PROFILE_BY_USERNAME_DONE: 'FETCH_PROFILE_BY_USERNAME_DONE',
	FETCH_PROFILE_BY_USERNAME_ERROR: 'FETCH_PROFILE_BY_USERNAME_ERROR',

	UNLOAD_PROFILE: 'UNLOAD_PROFILE'
};
