export default {
    
	FETCH_PROFILE_BY_USERNAME_REQUESTED: 'FETCH_PROFILE_BY_USERNAME_REQUESTED',
	FETCH_PROFILE_BY_USERNAME_DONE: 'FETCH_PROFILE_BY_USERNAME_DONE',
	FETCH_PROFILE_BY_USERNAME_ERROR: 'FETCH_PROFILE_BY_USERNAME_ERROR',

	UNLOAD_PROFILE: 'UNLOAD_PROFILE'
};
