export default {
	FETCH_ARTICLE_REQUESTED: 'FETCH_ARTICLE_REQUESTED',
	FETCH_ARTICLE_DONE: 'FETCH_ARTICLE_DONE',
	FETCH_ARTICLE_ERROR: 'FETCH_ARTICLE_ERROR',


	CREATE_ARTICLE_REQUESTED: 'CREATE_ARTICLE_REQUESTED',
	CREATE_ARTICLE_DONE: 'CREATE_ARTICLE_DONE',
	CREATE_ARTICLE_ERROR: 'CREATE_ARTICLE_ERROR',

	UPDATE_ARTICLE_REQUESTED: 'UPDATE_ARTICLE_REQUESTED',
	UPDATE_ARTICLE_DONE: 'UPDATE_ARTICLE_DONE',
	UPDATE_ARTICLE_ERROR: 'UPDATE_ARTICLE_ERROR',

	DELETE_ARTICLE_REQUESTED: 'DELETE_ARTICLE_REQUESTED',
	DELETE_ARTICLE_DONE: 'DELETE_ARTICLE_DONE',
	DELETE_ARTICLE_ERROR: 'DELETE_ARTICLE_ERROR',

	UNLOAD_ARTICLE: 'UNLOAD ARTICLE'
};
