export default {
	FETCH_SINGLE_ARTICLE_REQUEST: 'FETCH_SINGLE_ARTICLE_REQUEST',
	FETCH_SINGLE_ARTICLE_DONE: 'FETCH_SINGLE_ARTICLE_DONE',
	FETCH_SINGLE_ARTICLE_ERROR: 'FETCH_SINGLE_ARTICLE_ERROR',


	CREATE_SINGLE_ARTICLE_REQUEST: 'CREATE_SINGLE_ARTICLE_REQUEST',
	CREATE_SINGLE_ARTICLE_DONE: 'CREATE_SINGLE_ARTICLE_DONE',
	CREATE_SINGLE_ARTICLE_ERROR: 'CREATE_SINGLE_ARTICLE_ERROR',

	UPDATE_SINGLE_ARTICLE_REQUEST: 'UPDATE_SINGLE_ARTICLE_REQUEST',
	UPDATE_SINGLE_ARTICLE_DONE: 'UPDATE_SINGLE_ARTICLE_DONE',
	UPDATE_SINGLE_ARTICLE_ERROR: 'UPDATE_SINGLE_ARTICLE_ERROR',

	DELETE_SINGLE_ARTICLE_REQUEST: 'DELETE_SINGLE_ARTICLE_REQUEST',
	DELETE_SINGLE_ARTICLE_DONE: 'DELETE_SINGLE_ARTICLE_DONE',
	DELETE_SINGLE_ARTICLE_ERROR: 'DELETE_SINGLE_ARTICLE_ERROR',

	UNLOAD_SINGLE_ARTICLE: 'UNLOAD SINGLE_ARTICLE'
};
