export default {
    
 SIGN_UP_REQUESTED : 'SIGN_UP_REQUESTED',
 SIGN_UP_DONE : 'SIGN_UP_DONE',
 SIGN_UP_ERROR : 'SIGN_UP_ERROR',

 SIGN_IN_REQUESTED : 'SIGN_IN_REQUESTED',
 SIGN_IN_DONE : 'SIGN_IN_DONE',
 SIGN_IN_ERROR : 'SIGN_IN_ERROR',

 UPDATE_USER_REQUESTED : 'UPDATE_USER_REQUESTED',
 UPDATE_USER_DONE : 'UPDATE_USER_DONE',
 UPDATE_USER_ERROR : 'UPDATE_USER_ERROR'

}