export default {
	SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
	SIGN_UP_DONE: 'SIGN_UP_DONE',
	SIGN_UP_ERROR: 'SIGN_UP_ERROR',

	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_DONE: 'LOGIN_DONE',
	LOGIN_ERROR: 'LOGIN_ERROR',

	UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
	UPDATE_USER_DONE: 'UPDATE_USER_DONE',
	UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',

	LOG_OUT: 'LOG_OUT',

	CLEAR_ERROR: 'CLEAR_ERROR'
};
