export default {
	FETCH_TAGS_BY_MOST_POPULAR_REQUEST: 'FETCH_TAGS_BY_MOST_POPULAR_REQUEST',
	FETCH_TAGS_BY_MOST_POPULAR_DONE: 'FETCH_TAGS_BY_MOST_POPULAR_DONE',
	FETCH_TAGS_BY_MOST_POPULAR_ERROR: 'FETCH_TAGS_BY_MOST_POPULAR_ERROR',

	GET_TAG_NAME: 'GET_TAG_NAME',
	REMOVE_TAG_NAME: 'REMOVE_TAG_NAME',

	UNLOAD_TAGS: 'UNLOAD_TAGS'

};
